#!/usr/bin/env bash
# Generate a static device list from Bonjour, for development on macOS.
#
# macOS runs mDNSResponder, which owns UDP port 5353 exclusively, so the zeroconf
# backend receives nothing. This script asks Bonjour instead and writes the result as a
# discovery.static block. Production on TrueNAS SCALE uses the avahi backend and needs
# none of this.
#
# Usage: scripts/macos-static-config.sh [browse-seconds] > devices.yaml
set -uo pipefail

WAIT="${1:-8}"

# srv_records prints "instance<TAB>host<TAB>port<TAB>kind" for one service type.
#
# dns-sd -Z never exits, so it is time-boxed. Its SRV lines look like:
#   <instance>._shelly._tcp   SRV   0 0 80 <Host>.local. ; Replace with ...
# Instance names may contain spaces, which dns-sd escapes as \032.
srv_records() {
  local service="$1" kind="$2"
  timeout "$WAIT" dns-sd -Z "$service" local 2>/dev/null |
    awk -v kind="$kind" -v svc="$service" '
      $2 == "SRV" {
        host = $6
        sub(/\.$/, "", host)
        id = $1
        sub("\\." svc "$", "", id)
        gsub(/\\032/, " ", id)
        print id "\t" host "\t" $5 "\t" kind
      }'
}

# resolve prints the first IPv4 address for a .local hostname.
resolve() {
  timeout 4 dns-sd -G v4 "$1" 2>/dev/null |
    awk '$1 ~ /^[0-9][0-9]:/ && $6 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ { print $6; exit }'
}

# slug turns a display name into an identifier that is safe and stable in YAML.
slug() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//; s/-$//'
}

echo "# Generated by scripts/macos-static-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
echo "# Addresses are a snapshot. Regenerate after a DHCP change."
echo "discovery:"
echo "  sources: [static]"
echo "  static:"

{ srv_records _shelly._tcp shelly; srv_records _esphomelib._tcp esphome; } |
  sort -u |
  while IFS=$'\t' read -r id host port kind; do
    [ -n "${host:-}" ] || continue
    addr="$(resolve "$host")"
    if [ -z "$addr" ]; then
      echo "warning: $id ($host) did not resolve; skipped" >&2
      continue
    fi
    printf '    - {id: %s, kind: %s, address: %s, port: %s}\n' "$(slug "$id")" "$kind" "$addr" "$port"
  done
